name: Build Goose iOS

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select latest Xcode
        run: |
          sudo xcode-select -s /Applications/Xcode.app

      - name: Install Rust
        run: |
          curl https://sh.rustup.rs -sSf | sh -s -- -y
          source $HOME/.cargo/env
          rustup target add aarch64-apple-ios

      - name: Build Rust Core
        run: |
          source $HOME/.cargo/env
          cd Rust/core
          pwd
          ls
          cargo build --release

      - name: Resolve Swift Packages
        run: |
          xcodebuild \
            -resolvePackageDependencies \
            -project GooseSwift.xcodeproj

      - name: List Project Information
        run: |
          xcodebuild -list -project GooseSwift.xcodeproj

      - name: Archive iOS App
        run: |
          xcodebuild clean archive \
            -project GooseSwift.xcodeproj \
            -scheme GooseSwift \
            -configuration Release \
            -destination "generic/platform=iOS" \
            -archivePath build/Goose.xcarchive \
            CODE_SIGNING_ALLOWED=NO \
            SKIP_INSTALL=NO

      - name: Export IPA
        run: |
          mkdir -p build/ipa

          xcodebuild -exportArchive \
            -archivePath build/Goose.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath build/ipa

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: Goose-IPA
          path: build/ipa
